name: 'Cloudflare Access Proxy'
description: 'Start a local reverse proxy that injects Cloudflare Access headers'
branding:
  icon: cloud
  color: orange
inputs:
  cf-access-client-id:
    required: true
    description: 'Cloudflare Access Client ID'
  cf-access-client-secret:
    required: true
    description: 'Cloudflare Access Client Secret'
  target-url:
    required: true
    description: 'The destination URL to proxy to (e.g., https://my-service.cloudflareaccess.com)'
  listen-port:
    required: false
    description: 'The port that the proxy will listen on (default is 8080)'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install NPM dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Start proxy in background
      run: node ${{ github.action_path }}/src/proxy.js > proxy.log 2>&1 &
      shell: bash
      env:
        CF_ACCESS_CLIENT_ID: ${{ inputs.cf-access-client-id }}
        CF_ACCESS_CLIENT_SECRET: ${{ inputs.cf-access-client-secret }}
        TARGET_URL: ${{ inputs.target-url }}
        LISTEN_PORT: ${{ inputs.listen-port }}
